### ISSUE TITLE
Magister agenda ophalen werkt niet meer?

### ISSUE THREAD

**Issue by RepsaJN** [Stanvk/Magister#29]
```
2015-11-182015-12-10

Magister agenda

exception 'GuzzleHttp\Exception\ParseException' with message 'Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON' in /var/www/html/magister-agenda/vendor/guzzlehttp/guzzle/src/Message/Response.php:148 Stack trace: #0 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php(83): GuzzleHttp\Message\Response->json() #1 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php(147): Magister\Services\Database\Connection->Magister\Services\Database\{closure}(Object(Magister\Services\Database\Connection), 'personen/:id/af...', Array) #2 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php(123): Magister\Services\Database\Connection->runQueryCallback('personen/:id/af...', Array, Object(Closure)) #3 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php(84): Magister\Services\Database\Connection->run('personen/:id/af...', Array, Object(Closure)) #4 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Query/Builder.php(122): Magister\Services\Database\Connection->select('personen/:id/af...', Array) #5 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Query/Builder.php(112): Magister\Services\Database\Query\Builder->runSelect() #6 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Elegant/Builder.php(106): Magister\Services\Database\Query\Builder->get() #7 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Elegant/Builder.php(65): Magister\Services\Database\Elegant\Builder->getModels() #8 /var/www/html/magister-agenda/getMagister.php(31): Magister\Services\Database\Elegant\Builder->get() #9 /var/www/html/magister-agenda/test_oud.php(22): getMagisterData('xxx', 'xxx', 'xxx', Array) #10 {main} Next exception 'Magister\Services\Database\QueryException' with message 'Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON (Query: personen/:id/afspraken, Array ( [van] => 2015-11-18 [tot] => 2015-12-10 ) )' in /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php:154 Stack trace: #0 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php(123): Magister\Services\Database\Connection->runQueryCallback('personen/:id/af...', Array, Object(Closure)) #1 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Connection.php(84): Magister\Services\Database\Connection->run('personen/:id/af...', Array, Object(Closure)) #2 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Query/Builder.php(122): Magister\Services\Database\Connection->select('personen/:id/af...', Array) #3 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Query/Builder.php(112): Magister\Services\Database\Query\Builder->runSelect() #4 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Elegant/Builder.php(106): Magister\Services\Database\Query\Builder->get() #5 /var/www/html/magister-agenda/vendor/stanvk/magister/src/Magister/Services/Database/Elegant/Builder.php(65): Magister\Services\Database\Elegant\Builder->getModels() #6 /var/www/html/magister-agenda/getMagister.php(31): Magister\Services\Database\Elegant\Builder->get() #7 /var/www/html/magister-agenda/test_oud.php(22): getMagisterData('xxx', 'xxx', 'xxx', Array) #8 {main}`
```

```

        try {
                $magister = new Magister($school, $username, $passwo$
        }        
        catch (Exception $e) {

                echo '<br><br>';
                echo 'Magister inlog';
                echo '<br><br>';
                echo $e;
                echo '<br><br>';
        }

        try {
        $appointments = Appointment::where('van', $begin)->where('to$
                echo $appointments;
                $result = json_decode($appointments, true);
        } catch (Exception $e) {
                echo '<br><br>';
                echo 'Magister agenda';
                echo '<br><br>';
                echo $e;
                echo '<br><br>';
                return $e;
        }

```

Vorige week werkte onze implentatie van onze huiswerk ophaal module nog naar behoren. Maar er lijkt iets te zijn veranderd, wij krijgen deze error. Zoals je ziet, lukt het inloggen wel, maar de magister agenda zelf niet. 

```

php --version
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 15 2016 15:55:17) 

```

```
cat composer.json 
{
    "require": {
        "stanvk/magister": "~2.0"
    }
}
```

**Comment by elisaado** [comment]
Ik heb hetzelfde probleem....
Nu wel een rare error....
p.s. je vergeet hier een ;  

```
        try {
                $magister = new Magister($school, $username, $passwo$
        }    
```

**Comment by jbehrens94** [comment]
Je kunt gewoon eerst eens kijken of je een andere response terugkrijgt in bijv. Postman en daarop je code aanpassen, lijkt mij. Weinig zin om hier te gaan klagen als je niet zelf debugt en gelijk een PR doet.

**Comment by elisaado** [comment]
Woooow rustig... Ik (en waarschijnlijk ook de topic starter) klaagden niet. Dit is de issue section. Dit is een issue.

**Comment by Kickwood** [comment]
Hebben jullie hier nog steeds last van? Ik heb meer informatie nodig om hier wat mee te kunnen, aangezien ik zelf na enig testen hier geen last van blijk te hebben.

Ik heb om te beginnen de response nodig van het desbetreffende request. Dit om te weten waar de malformed JSON mee te maken heeft; ofwel problemen met het inloggen, ofwel problemen met de response. Het makkelijkste lijkt mij om even snel een regeltje toe te voegen aan de code van de API om vervolgens de benodigde gegevens zo uit te lezen.

Open `Magister\Services\Database\Connection` en navigeer naar regel 81. Voeg daar vervolgens direct onder de volgende code toe:

``` php
var_dump($statement);
```

Dit zal alle gemaakte requests duidelijk onder elkaar zetten. Nu hoef je enkel nog even de response   naar `/afspraken` in de browser uit te lezen en compleet naar mij door te sturen. 

Overigens, in plaats van `json_decode()` op de Collection te gebruiken, is het makkelijker om de built-in method `toArray()` te gebruiken.

``` php
$result = $appointments->toArray();
```
